
import React, { useState, useRef, useEffect } from 'react';
import { TYPING_CHALLENGE_DATA } from '../constants';
import { ScoreEntry } from '../types';

const CHALLENGE_POOL = [
  "Science is about knowing; engineering is about doing. - Henry Petroski",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "The human footprint in the sand of time is not made by sitting down. - Lord Kelvin",
  "One man's magic is another man's engineering. - Robert Heinlein",
  "Navier-Stokes equations describe the motion of viscous fluid substances.",
  "Manufacturing is more than just putting parts together. It is perfecting the engineering.",
  "Geometric Dimensioning and Tolerancing ensures component interchangeability through precise control.",
  "The second law of thermodynamics states that total entropy of an isolated system can never decrease.",
  "Skyscrapers move. The Burj Khalifa is designed to sway up to 1.5 meters at the very top.",
  "Mechanical advantage is a measure of the force amplification achieved by using a tool.",
  "Bernoulli's principle states that an increase in the speed of a fluid occurs with a decrease in pressure.",
  "Hydraulic systems use pressurized fluids to transmit power and multiply force.",
  "The first industrial robot, Unimate, joined the assembly line at General Motors in 1961.",
  "Finite Element Analysis is a numerical method for solving problems of engineering and physics.",
  "Computational Fluid Dynamics uses numerical analysis to solve problems that involve fluid flows.",
  "The Carnot cycle is an ideal reversible closed thermodynamic cycle.",
  "Entropy is a measure of the molecular disorder or randomness in a system.",
  "Enthalpy is a property defined as the sum of internal energy and the product of pressure and volume.",
  "Conduction is the transfer of heat between substances that are in direct contact.",
  "Radiation is energy that comes from a source and travels through space at the speed of light.",
  "A heat sink is a passive heat exchanger that transfers heat generated by a device to a fluid medium."
];

const TypingChallenge: React.FC = () => {
  const [shuffledPhrases, setShuffledPhrases] = useState<string[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [userInput, setUserInput] = useState('');
  const [startTime, setStartTime] = useState<number | null>(null);
  const [wpm, setWpm] = useState(0);
  const [accuracy, setAccuracy] = useState(100);
  const [mistakes, setMistakes] = useState(0);
  const [totalKeys, setTotalKeys] = useState(0);
  const [isFinished, setIsFinished] = useState(false);
  const [history, setHistory] = useState<{phrase: string, wpm: number, accuracy: number}[]>([]);
  const [initials, setInitials] = useState('');
  const [personalHistory, setPersonalHistory] = useState<ScoreEntry[]>([]);
  const [showScoreEntry, setShowScoreEntry] = useState(false);
  const [isInputFocused, setIsInputFocused] = useState(false);
  
  const inputRef = useRef<HTMLInputElement>(null);
  const timerRef = useRef<number | null>(null);

  useEffect(() => {
    const saved = localStorage.getItem('mech_high_scores_registry');
    if (saved) {
      try {
        const localScores: ScoreEntry[] = JSON.parse(saved);
        setPersonalHistory(localScores.sort((a, b) => b.score - a.score).slice(0, 20));
      } catch (e) {}
    }
  }, []);

  useEffect(() => {
    const shuffled = [...CHALLENGE_POOL].sort(() => 0.5 - Math.random());
    setShuffledPhrases(shuffled.slice(0, 5));
  }, []);

  const fullRawPhrase = shuffledPhrases[currentIndex] || "";
  const parts = fullRawPhrase.split(' - ');
  const targetQuote = parts[0];
  const targetAuthor = parts.length > 1 ? parts[1] : null;

  useEffect(() => {
    if (inputRef.current && !isFinished && !showScoreEntry) {
        inputRef.current.focus();
    }
  }, [currentIndex, isFinished, showScoreEntry]);

  useEffect(() => {
    if (startTime && !isFinished) {
      timerRef.current = window.setInterval(() => {
        const timeElapsed = (Date.now() - startTime) / 60000;
        if (timeElapsed > 0.005) {
          const words = userInput.length / 5;
          setWpm(Math.round(words / timeElapsed));
        }
      }, 500);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
    }
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [startTime, isFinished, userInput.length]);

  const nextPhase = () => {
    const endTime = Date.now();
    const timeElapsed = (endTime - (startTime || endTime)) / 60000;
    const words = targetQuote.length / 5;
    const finalWpm = Math.round(words / (timeElapsed || 0.001));
    const finalAccuracy = totalKeys > 0 ? Math.max(0, Math.round(((totalKeys - mistakes) / totalKeys) * 100)) : 100;
    
    setHistory(prev => [...prev, { phrase: targetQuote, wpm: finalWpm, accuracy: finalAccuracy }]);
    
    setUserInput('');
    setStartTime(null);
    setMistakes(0);
    setTotalKeys(0);
    setAccuracy(100);
    setWpm(0);

    if (currentIndex < shuffledPhrases.length - 1) {
      setCurrentIndex(prev => prev + 1);
    } else {
      setIsFinished(true);
      setShowScoreEntry(true);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    
    if (!startTime && val.length > 0) {
      setStartTime(Date.now());
    }

    if (val.length > userInput.length) {
      setTotalKeys(prev => prev + 1);
      const lastChar = val[val.length - 1];
      const expectedChar = targetQuote[val.length - 1];
      if (lastChar !== expectedChar) {
        setMistakes(prev => prev + 1);
      }
    }

    const currentTotal = totalKeys + (val.length > userInput.length ? 1 : 0);
    const currentMistakes = mistakes + (val.length > userInput.length && val[val.length-1] !== targetQuote[val.length-1] ? 1 : 0);
    if (currentTotal > 0) {
      setAccuracy(Math.max(0, Math.round(((currentTotal - currentMistakes) / currentTotal) * 100)));
    }

    if (val === targetQuote) {
      nextPhase();
    } else {
      setUserInput(val);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      if (userInput.length >= targetQuote.length) {
        nextPhase();
      }
    }
  };

  const reInitializeSystem = () => {
    const shuffled = [...CHALLENGE_POOL].sort(() => 0.5 - Math.random());
    setShuffledPhrases(shuffled.slice(0, 5));
    setCurrentIndex(0);
    setUserInput('');
    setStartTime(null);
    setIsFinished(false);
    setShowScoreEntry(false);
    setInitials('');
    setWpm(0);
    setAccuracy(100);
    setMistakes(0);
    setTotalKeys(0);
    setHistory([]);
  };

  const saveScoreToRegistry = () => {
    const avgWpm = Math.round(history.reduce((a, b) => a + b.wpm, 0) / history.length);
    const avgAcc = Math.round(history.reduce((a, b) => a + b.accuracy, 0) / history.length);
    const score = Math.round(avgWpm * (avgAcc / 100) * 10);
    
    const newEntry: ScoreEntry = {
      initials: (initials || '??').substring(0, 2).toUpperCase(),
      wpm: avgWpm,
      accuracy: avgAcc,
      score,
      timestamp: Date.now()
    };

    const saved = localStorage.getItem('mech_high_scores_registry');
    let localHistory: ScoreEntry[] = [];
    if (saved) {
      try {
        localHistory = JSON.parse(saved);
      } catch (e) {}
    }
    localHistory.push(newEntry);
    const sorted = localHistory.sort((a, b) => b.score - a.score).slice(0, 50);
    localStorage.setItem('mech_high_scores_registry', JSON.stringify(sorted));
    setPersonalHistory(sorted.slice(0, 20));
    setShowScoreEntry(false);
  };

  const renderTargetQuote = () => {
    if (!targetQuote) return null;
    return (
      <div className="flex flex-col items-center gap-2">
        <div className="relative inline text-center font-mono leading-relaxed whitespace-pre-wrap max-w-2xl px-2 text-xs md:text-xl lg:text-2xl">
          {targetQuote.split('').map((char, i) => {
            const isTyped = i < userInput.length;
            let color = 'text-white/20';
            if (isTyped) {
              color = userInput[i] === char ? 'text-[#00FF41]' : 'text-red-500 bg-red-900/30';
            }
            return (
              <span key={i} className={`${color} transition-colors duration-100`}>{char}</span>
            );
          })}
        </div>
        {targetAuthor && (
          <div className="text-[9px] md:text-xs opacity-40 italic font-mono mt-2 transition-all">
            — {targetAuthor}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className={`max-w-4xl mx-auto flex flex-col gap-4 animate-in fade-in duration-700 pb-10 transition-all duration-500 ${isInputFocused ? 'pt-4 md:pt-0' : ''}`}>
      
      <div className={`flex justify-between items-end border-b border-[#00FF41]/30 pb-4 transition-all duration-300 ${isInputFocused ? 'opacity-40 md:opacity-100' : 'opacity-100'}`}>
        <div className="space-y-1">
          <h2 className="text-base md:text-3xl font-bold glow-text tracking-widest uppercase">
            {TYPING_CHALLENGE_DATA.header}
          </h2>
          <p className="text-[8px] md:text-[10px] text-cyan-400 font-mono tracking-widest">
            PHASE: {currentIndex + 1} / {shuffledPhrases.length}
          </p>
        </div>
        
        <div className="flex gap-4 md:gap-8 text-right">
          <div className="flex flex-col">
            <span className="text-[7px] md:text-[10px] opacity-40 uppercase tracking-widest">WPM</span>
            <span className="text-xs md:text-2xl font-bold text-yellow-400">{wpm || '--'}</span>
          </div>
          <div className="flex flex-col">
            <span className="text-[7px] md:text-[10px] opacity-40 uppercase tracking-widest">ACC</span>
            <span className="text-xs md:text-2xl font-bold text-pink-400">{accuracy}%</span>
          </div>
        </div>
      </div>

      <div className={`relative border border-[#00FF41]/40 bg-black/95 p-4 md:p-12 shadow-2xl transition-all duration-300 min-h-[280px] md:min-h-[400px] flex flex-col justify-center rounded-sm ${isInputFocused ? 'ring-2 ring-[#00FF41]/20 transform -translate-y-4 md:translate-y-0' : ''}`}>
        
        {!isFinished && (
          <div className="space-y-6 md:space-y-12">
            <div className="flex items-center justify-center min-h-[100px] md:min-h-[160px]">
              {renderTargetQuote()}
            </div>

            <div className="relative max-w-xl mx-auto w-full">
              <div className={`w-full relative py-3 border-b-2 transition-colors ${isInputFocused ? 'border-[#00FF41]' : 'border-[#00FF41]/40'}`}>
                <div className="text-xs md:text-2xl font-mono min-h-[1.5em] text-center pointer-events-none break-all whitespace-pre-wrap px-4">
                  <span className="text-white">
                    {userInput}
                    <span className="inline-block w-[1ch] h-[1.1em] bg-[#00FF41] animate-pulse align-middle ml-[1px] shadow-[0_0_10px_#00FF41]" />
                  </span>
                  {!userInput && !isInputFocused && (
                    <span className="opacity-20 italic text-[10px] md:text-base tracking-widest">BEGIN_TYPING_PROTOCOL...</span>
                  )}
                </div>
                
                <input
                  ref={inputRef}
                  type="text"
                  value={userInput}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  onFocus={() => setIsInputFocused(true)}
                  onBlur={() => setIsInputFocused(false)}
                  className="absolute inset-0 w-full h-full bg-transparent outline-none text-transparent caret-transparent font-mono z-30 cursor-default"
                  autoFocus
                  autoComplete="off"
                  spellCheck="false"
                />
              </div>
              
              {userInput.length >= targetQuote.length && (
                <div className="text-center mt-4 animate-bounce">
                    <p className="text-[9px] text-[#00FF41] font-bold tracking-[0.2em] uppercase">Press [ENTER] to continue</p>
                </div>
              )}
            </div>
          </div>
        )}

        {isFinished && showScoreEntry && (
          <div className="text-center space-y-8 animate-in zoom-in duration-500 py-6">
            <h3 className="text-xl md:text-4xl font-bold text-[#00FF41] glow-text italic tracking-tighter uppercase">MISSION_COMPLETE</h3>
            <div className="max-w-xs mx-auto space-y-4">
              <p className="text-[9px] md:text-xs opacity-50 uppercase tracking-widest">ENTER_OPERATOR_ID [2 CHARS]</p>
              <input
                type="text"
                value={initials}
                onChange={(e) => setInitials(e.target.value.substring(0, 2).toUpperCase())}
                className="w-full bg-black/50 border border-[#00FF41]/40 text-center text-4xl md:text-6xl font-mono p-4 focus:border-[#00FF41] outline-none text-[#00FF41] rounded"
                placeholder="__"
                autoFocus
                onKeyDown={(e) => e.key === 'Enter' && initials.length > 0 && saveScoreToRegistry()}
              />
              <button 
                onClick={saveScoreToRegistry}
                disabled={initials.length === 0}
                className="w-full py-4 bg-[#00FF41] text-black font-bold hover:bg-white transition-all uppercase text-xs md:text-sm tracking-[0.3em] disabled:opacity-20 shadow-[0_0_30px_rgba(0,255,65,0.2)]"
              >
                COMMIT_DATA
              </button>
            </div>
          </div>
        )}

        {isFinished && !showScoreEntry && (
          <div className="text-center space-y-8 animate-in zoom-in duration-500 py-6">
             <div className="flex justify-center gap-6 md:gap-12">
                <div className="text-center">
                   <p className="text-[8px] md:text-[10px] text-white/40 font-bold uppercase mb-1">FINAL_WPM</p>
                   <p className="text-xl md:text-5xl font-bold text-yellow-400 font-mono">
                    {Math.round(history.reduce((a,b)=>a+b.wpm,0)/history.length)}
                   </p>
                </div>
                <div className="text-center">
                   <p className="text-[8px] md:text-[10px] text-white/40 font-bold uppercase mb-1">AVG_ACC</p>
                   <p className="text-xl md:text-5xl font-bold text-pink-400 font-mono">
                    {Math.round(history.reduce((a,b)=>a+b.accuracy,0)/history.length)}%
                   </p>
                </div>
             </div>
             <button 
              onClick={reInitializeSystem}
              className="px-6 md:px-12 py-3 md:py-4 border-2 border-[#00FF41] text-[#00FF41] font-bold hover:bg-[#00FF41] hover:text-black transition-all uppercase text-[9px] md:text-xs tracking-[0.4em]"
            >
              NEW_SIMULATION
            </button>
          </div>
        )}
      </div>

      <div className={`grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-8 transition-opacity duration-300 ${isInputFocused ? 'opacity-0 md:opacity-100 pointer-events-none md:pointer-events-auto' : 'opacity-100'}`}>
        <div className="border border-white/10 bg-black/60 p-5 rounded">
          <h4 className="text-[10px] font-bold text-white/40 mb-3 uppercase tracking-widest border-b border-white/10 pb-2">PERSONAL_BESTS</h4>
          <div className="space-y-2 max-h-32 overflow-y-auto custom-scrollbar">
            {personalHistory.length > 0 ? personalHistory.slice(0, 5).map((s, i) => (
              <div key={i} className="flex justify-between text-[10px] font-mono p-1 border-b border-white/5 bg-white/5">
                <span className="text-cyan-400">#0{i+1} <span className="text-white ml-2">{s.initials}</span></span>
                <span className="text-[#00FF41]">{s.wpm} WPM // {s.score} PTS</span>
              </div>
            )) : <p className="text-[10px] opacity-20 italic">AWAITING_DATA...</p>}
          </div>
        </div>

        <div className="border border-white/10 bg-black/60 p-5 rounded space-y-4">
          <h4 className="text-[10px] font-bold text-white/40 mb-3 uppercase tracking-widest border-b border-white/10 pb-2">GUIDELINES</h4>
          <div className="space-y-2 text-[10px] font-mono leading-relaxed opacity-60">
            <p>1. ACCURACY OVER RAW SPEED.</p>
            <p>2. SCORE = WPM * (ACC / 100) * 10</p>
            <p className="text-[9px] italic opacity-40">Press [ENTER] to advance once text length is reached.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TypingChallenge;
